name: covidviewerflutter
description: A Flutter application to watch covid statistics.

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  flutter_picker: ^1.1.3
  provider: ^4.0.4
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path_android: "assets/icons/ic_launcher_xxxhdpi.png"
  image_path_ios: "assets/icons/ic_launcher_xxxhdpi.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

flutter:

  uses-material-design: true

  assets:
    - assets/countries.json
